=== fdepablo/WsLMSGI/06_XSD/02_XSD_Libro.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <annotation>
        <documentation>
            Esquema que marca la estructura de un libro de la libreria "Paco's Library"
         </documentation>
    </annotation>
    <!-- El nodo raiz se llama Libro-->
    <element name="Libro">
        <complexType>
            <sequence>
                <element name="Titulo" type="string" />
                <element name="Autor" type="string" minOccurs="1" maxOccurs="unbounded" />
                <element name="Editorial">
                    <complexType>
                        <sequence>
                            <element name="nombre" type="string"></element>
                            <element name="direccion" type="string"></element>
                        </sequence>
                    </complexType>  
                </element>
                <!-- Optativa la fecha de edicion -->
                <element name="fecha_edicion" type="date" minOccurs="0"></element>

                <!-- Algunos casos mas particulares -->
                <!--
                Elemento vacio simple, estos elementos deberian de ser autoexplicativos y que
                el tener la etiqueta o no tenerla ya aportaria informaciÃ³n.            
                Al poner minOccurs a 0, lo estamos haciendo optativo
                -->
                <element name="bestseller" minOccurs="0">
                    <complexType />
                </element>

                <!-- Elemento vacio con un atributo-->
                <element name="paginas">
                    <complexType>
                        <attribute name="valor" use="required"></attribute>
                    </complexType>
                </element>

                <!-- Ejemplo de nodo simple de tipo String pero con atributos -->
                <element name="prologo">
                    <complexType>
                        <simpleContent>
                            <extension base="string">
                                <attribute name="pagina"></attribute>
                            </extension>
                        </simpleContent>
                    </complexType>
                </element>
            </sequence>
            <!-- Los atributos son optativos por defecto-->
            <attribute name="precio" type="double"></attribute>
            <!-- Podemos hacer los atributos obligatorios -->
            <attribute name="id" type="integer" use="required"></attribute>
        </complexType>
    </element>
</schema>

=== fdepablo/WsLMSGI/06_XSD/02_XSD_Libro_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<Libro id="2" precio="30.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "02_XSD_Libro.xsd">
    <Titulo>Fray Perico y su borrico</Titulo>
    <Autor>Yo no</Autor>
    <Editorial>
        <nombre>Espasa</nombre>
        <direccion>Calle la plata 29</direccion>
    </Editorial>
    <fecha_edicion>2011-11-04</fecha_edicion>
    <paginas valor="154" />
    <prologo pagina="5">
        Libro sobre un fraile que esta en una iglesia con un burro
    </prologo>
</Libro>
