=== fdepablo/WsLMSGI/06_XSD/04_XSD_ExpresionesRegulares.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="persona">
        <complexType>
            <sequence>
                <element name="posicion">
                    <simpleType>
                        <restriction base="string">
                             <!-- Cualquier digito -->
                            <pattern value="\d"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="letra">
                    <simpleType>
                        <restriction base="string">
                            <!-- Cualquier NO digito -->
                            <pattern value="\D"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="rango_numerico">
                    <simpleType>
                        <restriction base="integer">
                            <!-- Un rango comprendido entre el 0 y el 5 -->
                            <pattern value="[012345]"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="rango_de_letras_minusculas">
                    <simpleType>
                        <restriction base="string">
                            <!-- Un rango de letras, con un "-" decimos el principio del rango y 
                            el final del rango -->
                            <pattern value="[a-z]"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="rango_de_letras">
                    <simpleType>
                        <restriction base="string">
                            <!-- Un rango de letras minusculas o mayusculas -->
                            <pattern value="[a-zA-Z]"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="ejemplo_llaves">
                    <simpleType>
                        <restriction base="string">
                            <!-- Un rango de letras pero 8 letras exactamente -->
                            <pattern value="[a-zA-Z]{8}"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="ejemplo_llaves_2">
                    <simpleType>
                        <restriction base="string">
                            <!-- Un rengo de letras de 1 a 8 coincidencias -->
                            <pattern value="[a-zA-Z]{2,8}"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="DNI">
                    <simpleType>
                        <restriction base="string">
                            <!-- Validar un DNI -->
                            <pattern value="[0-9]{8}[A-Z]"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="conjunto_letras">
                    <simpleType>
                        <restriction base="string">
                            <!-- Solo admitimos el siguiente conjunto de letras -->
                            <pattern value="[abcABCzZ]"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="conjunto_letras_con_repeticion">
                    <simpleType>
                        <restriction base="string">
                            <!-- Solo admitimos el siguiente conjunto de letras de 1 a 5 veces -->
                            <pattern value="[abcABCzZ]{1,5}"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="matricula">
                    <simpleType>
                        <restriction base="string">
                            <!-- Una matricula de un coche-->
                            <pattern value="[0-9]{4}-[BCDFGHJKLMNPQRSTVWXYZ]{3}"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="nombre_apellido">
                    <simpleType>
                        <restriction base="string">
                            <!-- nombre seguido de un espacio en blanco y luego un apellido-->
                            <pattern value="[A-Z]([a-z])+\s[A-Z]([a-z])+"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="nombre_apellidos">
                    <simpleType>
                        <restriction base="string">
                            <!-- nombre seguido de un espacio en blanco y luego un apeelido-->
                            <pattern value="([A-Z]([a-z])+(\s){0,1})+"></pattern>
                        </restriction>
                    </simpleType>
                </element>
                <element name="email">
                    <simpleType>
                        <restriction base="string">
                            <!-- nombre seguido de un espacio en blanco y luego un apeelido-->
                            <pattern value="[^@]+@[^\.]+\..+"></pattern>
                        </restriction>
                    </simpleType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== fdepablo/WsLMSGI/05_XSD/04_XSD_ExpresionesRegulares.xml
<?xml version="1.0" encoding="UTF-8"?>
<persona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "04_XSD_ExpresionesRegulares.xsd">
    <posicion>1</posicion>
    <letra>G</letra>
    <rango_numerico>4</rango_numerico>
    <rango_de_letras_minusculas>e</rango_de_letras_minusculas>
    <rango_de_letras>R</rango_de_letras>
    <ejemplo_llaves>abcdefgh</ejemplo_llaves>
    <ejemplo_llaves_2>abcdefgh</ejemplo_llaves_2>
    <DNI>12345678K</DNI>
    <conjunto_letras>a</conjunto_letras>
    <conjunto_letras_con_repeticion>abcAZ</conjunto_letras_con_repeticion>
    <matricula>1234-FTG</matricula>
    <nombre_apellido>Steve Rogers</nombre_apellido>
    <nombre_apellidos>Tony Stark Martinez</nombre_apellidos>
    <email>felix@uem.com</email>
</persona>
