=== fdepablo/WsLMSGI/05_XSD/02_XSD_Libro.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <annotation>
        <documentation>
            Esquema que marca la estructura de un libro de la libreria "Paco's Shop"
         </documentation>
    </annotation>
    <element name="Libro">
        <complexType>
            <sequence>
                <element name="Titulo" type="string" />
                <element name="Autor" type="string" minOccurs="1" maxOccurs="unbounded" />
                <element name="Editorial" type="string" default="Espasa" />
                <element name="fecha_edicion" type="date" minOccurs="0" maxOccurs="1"></element>
                <!--
                Elemento vacio simple, estos elementos deberian de ser autoexplicativos y que
                el tener la etiqueta o no tenerla ya aportaria informaciÃ³n.            
                Al poner minOccurs a 0, lo estamos haciendo optativo
                -->
                <element name="bestseller" minOccurs="0">
                    <complexType />
                </element>

                <!-- Elemento vacio con un atributo-->
                <element name="paginas">
                    <complexType>
                        <attribute name="valor" use="required"></attribute>
                    </complexType>
                </element>

                <!-- Ejemplo de nodo simple de tipo String pero con atributos -->
                <element name="prologo">
                    <complexType>
                        <simpleContent>
                            <extension base="string">
                                <attribute name="pagina"></attribute>
                            </extension>
                        </simpleContent>
                    </complexType>
                </element>
            </sequence>
            <!-- Los atributos son optativos por defecto-->
            <attribute name="precio" type="double"></attribute>
            <!-- Podemos hacer los atributos obligatorios -->
            <attribute name="id" type="integer" use="required"></attribute>
        </complexType>
    </element>
</schema>

=== fdepablo/WsLMSGI/05_XSD/02_XSD_Libro_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<Libro id="1" precio="23.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "02_XSD_Libro.xsd">
    <Titulo>El planeta de los simios</Titulo>
    <Autor>Felix</Autor>
    <Autor>Ana</Autor>
    <Editorial>Panini</Editorial>
    <fecha_edicion>2012-11-12</fecha_edicion>
    <bestseller />
    <paginas valor="250" />
    <prologo pagina="3">
        Es un libro muy bonito :) en el cual se cuenta la vida de Maria de "o"
    </prologo>
</Libro>
